name: vat_calculator
description: VatClaulator Project for Small/Medium Company

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+5

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_holo_date_picker: ^1.0.1+2
  flutter_contacts: ^1.1.6
  dio: ^4.0.0
  animated_splash_screen: ^1.3.0
  pin_code_fields: ^7.3.0
  flutter_lints: ^1.0.0
  gender_picker: ^1.1.0
  flutter_svg: ^0.22.0
  provider: ^5.0.0
  grouped_list: ^5.1.2
  url_launcher: ^6.1.11
  json_path: ^0.3.1
  uuid: 3.0.5
  font_awesome_flutter: ^9.2.0
  data_table_2: ^2.1.1
  table_calendar: ^3.0.0
  loader_overlay: ^2.0.2+1
  flutter_spinkit: ^5.1.0
  chips_choice: ^2.0.1
  csc_picker: ^0.2.6
  sliding_up_panel: ^2.0.0+1
  animations: ^2.0.7
  desktop_window: 0.4.0
  intl: ^0.17.0
  expandable_page_view: ^1.0.11
  fl_chart: ^0.45.1
  persistent_bottom_nav_bar: ^4.0.2
  flutter_animation_progress_bar: ^2.0.1
  percent_indicator: ^4.2.3
  supercharged: ^2.1.1
  chopper: ^5.1.0
  json_annotation: ^4.4.0
  linked_scroll_controller:
  modal_bottom_sheet: ^2.1.2
  cool_dropdown: ^1.4.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.0.10
  syncfusion_flutter_xlsio: ^19.1.64-beta
  path_provider: ^2.0.14
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
  assets:
    - assets/images/
    - assets/imagescalendar/
    - assets/png/
    - assets/icons/
    - assets/logo/

  uses-material-design: true