name: vat_calculator
description: VatClaulator Project for Small/Medium Company

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+78

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_holo_date_picker: ^1.0.1+2
  dio: ^4.0.0
  firebase_core:
  firebase_auth: ^3.3.9
  cloud_firestore:
  pin_code_fields: ^7.3.0
  flutter_lints: ^1.0.0
  gender_picker: ^1.1.0
  flutter_svg: ^0.22.0
  provider: ^5.0.0
  firebase_storage: ^10.0.5
  expansion_card: ^0.1.0
  grouped_list: ^1.3.1
  url_launcher: ^6.0.12
  json_path: ^0.3.1
  uuid: 3.0.5
  font_awesome_flutter: ^9.2.0
  data_table_2: ^2.1.1
  table_calendar: ^3.0.0
  loader_overlay: ^2.0.2+1
  flutter_spinkit: ^5.1.0
  syncfusion_flutter_calendar: ^19.3.48
  chips_choice: ^2.0.1
  syncfusion_flutter_charts: ^19.3.56
  csc_picker: ^0.2.6
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_pdf: ^19.3.57-beta
  rflutter_alert: ^1.0.2
  animated_text_kit: ^4.2.1
  animations: ^1.0.0
  google_sign_in: ^4.5.1
  path_provider: ^2.0.1
  path_provider_macos: ^2.0.0
  desktop_window: 0.4.0
  intl: ^0.17.0
  expandable_page_view: ^1.0.11
  fl_chart: ^0.45.1
  persistent_bottom_nav_bar: ^4.0.2
  firebase_messaging: ^11.2.11
  firebase_analytics: ^9.1.2
  flutter_animation_progress_bar: ^2.0.1
  percent_indicator: ^2.1.3
  grouped_buttons:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/

  uses-material-design: true