class ActionType{
  // Creation actions
  static String BRANCH_CREATION = 'CREAZIONE ATTIVITA';
  static String SUPPLIER_CREATION = 'CREAZIONE FORNITORE';
  static String SUPPLIER_ASSOCIATION = 'ASSOCIAZIONE FORNITORE';
  static String STORAGE_CREATION = 'CREAZIONE MAGAZZINO';
  static String EVENT_CREATION = 'CREAZIONE EVENTO';
  static String ORDER_CREATION = 'CREAZIONE ORDINE';
  static String DRAFT_ORDER_CREATION = 'CREAZIONE BOZZA ORDINE';
  static String PROVIDER_CREATION = 'CREAZIONE PROVIDER FATTURAZIONE';
  static String RECESSED_CREATION = 'CREAZIONE INCASSO';
  static String PRODUCT_CREATION = 'CREAZIONE PRODOTTO';
  static String ADD_PRODUCT_TO_STORAGE = 'AGGIUNTA PRODOTTO A MAGAZZINO';

  // Edit Actions
  static String BRANCH_EDIT = 'MODIFICA ATTIVITA';
  static String SUPPLIER_EDIT = 'MODIFICA FORNITORE';
  static String STORAGE_EDIT = 'MODIFICA MAGAZZINO';
  static String EVENT_EDIT = 'MODIFICA EVENTO';
  static String ORDER_EDIT = 'MODIFICA ORDINE';
  static String DRAFT_ORDER_EDIT = 'MODIFICA BOZZA ORDINE';
  static String PRODUCT_EDIT = 'MODIFICA PRODOTTO';

  // Delete Actions
  static String BRANCH_DELETE = 'CANCELLAZIONE ATTIVITA';
  static String SUPPLIER_DELETE = 'CANCELLAZIONE FORNITORE';
  static String STORAGE_DELETE = 'CANCELLAZIONE MAGAZZINO';
  static String EVENT_DELETE = 'CANCELLAZIONE EVENTO';
  static String ORDER_DELETE = 'CANCELLAZIONE ORDINE';
  static String PROVIDER_DELETE = 'CANCELLAZIONE PROVIDER FATTURAZIONE';
  static String PRODUCT_DELETE = 'CANCELLAZIONE PRODOTTO';
  static String REMOVE_PRODUCT_FROM_STORAGE = 'RIMOZIONE PRODOTTO DA MAGAZZINO';

  //LOAD/UNLOAD Storage
  static String STORAGE_LOAD = 'CARICO PRODOTTO IN MAGAZZINO';
  static String STORAGE_UNLOAD = 'SCARICO PRODOTTO DAL MAGAZZINO';

  //Send order
  static String SENT_ORDER = 'ORDINE INVIATO';
  static String RECEIVED_ORDER = 'ORDINE RICEVUTO';
}