import 'package:dio/dio.dart';
import 'package:vat_calculator/client/vatservice/model/response_fornitori.dart';
import 'package:vat_calculator/client/vatservice/model/expence_event_model.dart';
import 'package:vat_calculator/models/databundle.dart';
import 'model/branch_model.dart';
import 'model/event_model.dart';
import 'model/move_product_between_storage_model.dart';
import 'model/order_model.dart';
import 'model/product_model.dart';
import 'model/product_order_amount_model.dart';
import 'model/save_product_into_storage_request.dart';
import 'model/storage_model.dart';
import 'model/storage_product_model.dart';
import 'model/user_model.dart';
import 'model/workstation_model.dart';
import 'model/workstation_product_model.dart';

abstract class VatServiceInterface{

  Future<Response> performSaveUser(String firstName,String lastName, String phoneNumber, String eMail, String privileges, int relatedUserId);
  Future<Response> checkSpecialUser(UserModel usermodel);
 Future<Response> performSaveStorage({StorageModel storageModel});
  Future<Response> performSaveOrder({OrderModel orderModel});
  Future<List<ProductOrderAmountModel>> retrieveProductByOrderId(OrderModel orderModel);
  Future<Response> performSaveSupplier({SupplierModel anagraficaFornitore});
  Future<Response> performSaveBranch(BranchModel company);
  Future<Response> performSaveProduct({ProductModel product});
  Future<Response> performSaveProductIntoStorage({SaveProductToStorageRequest saveProductToStorageRequest});
  Future<Response> performSaveProductIntoOrder(double amount, int productId, int orderId);
  Future<Response> performUpdateProduct({ProductModel product});
  Future<Response> performDeleteProduct({ProductModel product});
  Future<Response> removeProductFromStorage({StorageProductModel storageProductModel});
  Future<UserModel> retrieveUserByEmail(String eMail);
  Future<List<BranchModel>> retrieveBranchesByUserId(int id);
  Future<List<StorageProductModel>> retrieveRelationalModelProductsStorage(int pkStorageId);
  Future<List<OrderModel>> retrieveOrdersByBranch(BranchModel currentBranch);
  Future<List<OrderModel>> retrieveOrderModelBySupplierIdAndBranchIdWhereStatusIsReceivedAndPaidIsFalse(int supplierId, int branchId);
  Future<List<OrderModel>> retrieveArchiviedOrdersByBranch(BranchModel currentBranch);
  Future<List<SupplierModel>> retrieveSuppliersListByBranch(BranchModel currentBranch);
  Future<List<ProductModel>> retrieveProductsBySupplier(SupplierModel currentSupplier);
  Future<List<ProductModel>> retrieveProductsByBranch(BranchModel branchModel);
  Future<List<StorageModel>> retrieveStorageListByBranch(BranchModel currentBranch);
  Future<List<BranchModel>> retrieveBranchByBranchId(String codeBranch);
  Future<List<UserModel>> retrieveUserListRelatedWithBranchByBranchId(BranchModel branchModel);
  Future<void> updateStock({List<StorageProductModel> currentStorageProductListForCurrentStorageUnload});
  Future<void> deleteOrder({OrderModel orderModel});
  Future<void> deleteStorage({StorageModel storageModel});
  Future<void> updateOrderStatus({OrderModel orderModel});
  Future<Response> addProviderDetailsToBranch({BranchModel branchModel});
  Future<List<SupplierModel>> retrieveSuppliersListByCode({String code});
  Future<int> addSupplierToCurrentBranch({SupplierModel supplierRetrievedByCodeToUpdateRelationTableBranchSupplier});
  Future<void> removeSupplierFromCurrentBranch({SupplierModel requestRemoveSupplierFromBranch});
  Future<Response> removeProviderFromBranch({BranchModel branchModel});
  Future<Response> createUserBranchRelation({int fkUserId, int fkBranchId, String accessPrivilege});
  Future<Response> updatePrivilegeForUserBranchRelation({int branchId, int userId, String privilegeType});
  Future<Response> updateFirebaseTokenForUserBranchRelation({int branchId, int userId, String token});
  Future<Response> removeUserBranchRelation({int branchId, int userId});
  Future<Response> performEditSupplier({SupplierModel anagraficaFornitore});
  Future<Response> removeProductFromOrder(ProductOrderAmountModel element);
  Future<Response> updateProductAmountIntoOrder(int pkOrderProductId, double amount, int pkProductId, int pk_order_id);
  Future<void>  updateUserData(UserDetailsModel userDetail);
  Future<List<WorkstationProductModel>> retrieveWorkstationProductModelByWorkstationId(WorkstationModel workstation);
  Future<List<EventModel>> retrieveEventsListByBranchId(BranchModel currentBranch);
  Future<List<EventModel>> retrieveEventsClosedListByBranchId(BranchModel currentBranch);
  Future updateWorkstationProductModel(List<WorkstationProductModel> workStationProdModelList);
  Future<Response> removeProductFromWorkstation(WorkstationProductModel prodModelWorkstation);
  Future<Response> updateEventModel(EventModel event);
  Future<List<String>> retrieveTokenList(BranchModel branchModel);

  Future<List<ExpenceEventModel>> retrieveEventExpencesByEventId(EventModel eventModel);
  Future<Response> updateEventExpenceModel(ExpenceEventModel expenceEventModel);
  Future<Response> createEventExpenceModel(ExpenceEventModel expenceEventModel);
  Future<Response> deleteEventExpenceModel(ExpenceEventModel expenceEventModel);
  Future<Response> moveProductBetweenStorage({List<MoveProductBetweenStorageModel> listMoveProductBetweenStorageModel});
  Future<Response> performEmptyStockStorage(StorageModel currentStorage);
}